# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='foto',
            field=models.ImageField(upload_to='fotos/'),
        ),
    ]
