# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20160415_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
